name: SharpSK
author: Sharpjaws
description: A addon made for automating your favourite plugins.
version: 1.6.1
main: me.sharpjaws.sharpSK.main
depend: [Skript]
softdepend: []
commands:
  sharpsk:
    description: All sharpsk commands
    aliases: [sharpsk,shsk]
