cfgver: "1.6.2"

# SharpSK Config
metrics: true
updater: true


# Plugin hooks
permissionsex: true
mythicmobs: true
jobsreborn: true
authmereloaded: true
lightapi: true
ucars: true
glowapi: true
mcmmo: true
coreprotect: true
multiverse: true
worldedit: true
worldguard: true
logblock: true
towny: true
sentinal: true
kingdoms: true
