name: SharpSK
author: Sharpjaws
description: A addon made for automating your favourite plugins.
version: ${project.version}
main: me.sharpjaws.sharpSK.SharpSK
depend: [Skript]
softdepend: [LightAPI,GlowAPI, Jobs, AuthMe, MythicMobs, PermissionsEx, ExertSK, SkRambled, Umbaska,PirateSK, mcMMO, uCars, Multiverse-Core, WorldEdit, WorldGuard, LogBlock, Towny, Kingdoms, Citizens, Sentinal]
loadbefore: [MassiveCore,Factions]
commands:
  sharpsk:
    description: All sharpsk commands
    aliases: [sharpsk,shsk]
